### ISSUE TITLE
fatal error: gelf.h: No such file or directory

### ISSUE THREAD

**Issue by jamesoncollins** [skiffos/SkiffOS#166]
On a clean pull of 2021.08, when running `make clean && SKIFF_CONFIG=virt/qemu make configure compile`, I get the following error while linux 5.14.11 is building:

```
/git/SkiffOS/workspaces/default/build/linux-5.14.11/tools/objtool/include/objtool/elf.h:10:10: fatal error: gelf.h: No such file or directory
 #include <gelf.h>
          ^~~~~~~~
compilation terminated.
```

**Comment by paralin** [comment]
@jamesoncollins I've enabled BR2_LINUX_KERNEL_NEEDS_HOST_LIBELF which should fix the issue. Please checkout "master" and try again. Thanks.

https://github.com/skiffos/SkiffOS/commit/f2832a5567f6fcccecb3b6bd4bdc737c94a8ab56
