### ISSUE TITLE
question: alternatives to docker, such as podman

### ISSUE THREAD

**Issue by bam80** [skiffos/SkiffOS#173]
I wonder if we actually need "serverfull" container solution here..

**Comment by paralin** [comment]
@bam80 No you don't need it; in fact, if you don't add apps/docker or skiff/core to SKIFF_CONFIG, it won't be compiled in at all.

At the moment we support runc, containerd, and docker in Buildroot but can easily add the others

I've been looking into using podman and/or crun and other lightweight container runtimes.
