### ISSUE TITLE
crun: use instead of runc for lower memory overhead

### ISSUE THREAD

**Issue by paralin** [skiffos/SkiffOS#185]
crun is a much lighter weight version of runc written in C instead of Go.

Switch to using crun instead of runc for containerd & docker.

**Comment by paralin** [comment]
Could it make sense to use Podman instead of Docker?

Docker would still be supported with the apps/docker flag, but skiff/core would now use apps/podman instead.

podman is a modern lighter weight alternative to Docker that has the same CLI and supports features like rootless containers.

Skiff/core would be rewritten to use the podman API instead of the Docker API.

Curently, I think the downsides of switching away from containerd outweigh the advantages.

**Comment by tianyuanhao** [comment]
>> Could you please review and test [this patch](http://patchwork.ozlabs.org/project/buildroot/patch/20221006140754.46144-1-tianyuanhao3@163.com/)?
>
> With that patch I can just deselect `runc` and enable `crun` instead?
> But I think _Docker_ also selects `runc`. Might need a few more conditional statements.

@paralin You can deselect `runc` and select `crun`. _Docker_ doesn't select `runc` but `containerd`.

**Comment by paralin** [comment]
Hey @tianyuanhao I'll try it out tonight, thanks for the reminder!

**Comment by tianyuanhao** [comment]
Let's get it merged before `2023.02`.

**Comment by paralin** [comment]
@tianyuanhao is it possible to add a config file for containerd to change it to use CRUN, as opposed to the symlink? I'll add my reviewed-by to the patch in the mailing list but they might not like the symlink approach

**Comment by tianyuanhao** [comment]
@paralin The _config approach_ is a bit complicated for `Buildroot`. The relationship between `crun` and `runc` is like `busybox` and `coreutils`, so I use _symlink approach_.

**Comment by paralin** [comment]
@tianyuanhao I submitted my reviewed-by on the mailing list and have merged your commit into the skiffos tree.

I'll try now to switch runc for crun on all skiffos default configs. Thanks!

**Comment by paralin** [comment]
This is now integrated.
