### ISSUE TITLE
podman: add support

### ISSUE THREAD

**Issue by paralin** [skiffos/SkiffOS#186]
Add support for podman under the apps/podman layer.

podman is a modern lighter weight alternative to Docker that has the same CLI and supports features like rootless containers.

The apps/podman layer could install a symlink so that the "docker" command aliases to "podman".

In future:

Skiff/core could be rewritten to use the podman API instead of the Docker API, and use a k8s Pod syntax to define containers instead of the skiff-core yaml config used today.

**Comment by Greylinux** [comment]
I was just thinking about this , this morning and I thought i'll create an issue for it.  Beat me to the punch ! 
Nice work @paralin

**Comment by tianyuanhao** [comment]
@paralin It feels complicated, you can refer to https://github.com/kubernetes/minikube/tree/master/deploy/iso/minikube-iso/package.

**Comment by paralin** [comment]
https://github.com/skiffos/buildroot/pull/20

Added a working podman package for both host & target.

There are a few TODOs remaining before merging.

**Comment by VarLad** [comment]
@paralin After podman, can I make a feature request for https://github.com/containers/toolbox and https://github.com/89luca89/distrobox ?
Those would be convenient to have on SkiffOS

**Comment by paralin** [comment]
@VarLad can do. In the meantime, though, you can probably accomplish the same thing with Skiff Core.

**Comment by aschamberger** [comment]
> In future:
> 
> Skiff/core could be rewritten to use the podman API instead of the Docker API, and use a k8s Pod syntax to define containers instead of the skiff-core yaml config used today.

Another alternative would be to implement the docker compose yaml format. This way you could just use docker compose on another OS and later migrate to SkiffOS. 

This would help in migrating my project to SkiffOS: I use docker compose on PiOS for my multiroom audio server to set up 8 container instances with all the container specific config within an env file. Via the profile feature I can only start the desired instances via `docker-compose -f compose.yml --profile on up -d` based on environment variables. I plan to build sometime a small supervisor container that allows changing the env file.

**Comment by paralin** [comment]
@aschamberger You can already use docker compose with `apps/compose` - Skiff Core is more meant to define long-running containers with ssh drop-in.

I don't know if the compose format would translate 1-1

**Comment by paralin** [comment]
All of the Buildroot packages for podman, catatonit, conmon, cni-plugins, crun have been submitted upstream & are in the SkiffOS tree. #235 tracks merging the config packages `apps/podman` and `apps/crun`

**Comment by paralin** [comment]
Podman support is merged to master with `apps/podman` 🥳

**Comment by tianyuanhao** [comment]
Hey @paralin, that's wonderful. I'm following [the relevant patches in Buildroot](http://patchwork.ozlabs.org/project/buildroot/list/?submitter=66856). I recommend that you refer to [these files in minikube](https://github.com/kubernetes/minikube/tree/master/deploy/iso/minikube-iso/package) and send v2 patches.

[Download the `crun` source package instead of using `git`](https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/crun/crun.mk#L9-L10) so no hacking is required.

**Comment by VarLad** [comment]
> @VarLad can do. In the meantime, though, you can probably accomplish the same thing with Skiff Core.

@paralin Any chance we can get a Fedora/Fedora-based image in skiff/core in the future? :sweat_smile:

**Comment by paralin** [comment]
@tianyuanhao I updated the package, thanks. Will resubmit.

By the way, some of those Buildroot packages in minikube could use an update. Replace `cni` with my `cni-plugins` for example, because `cni` doesn't even use the Go build infrastructure. The licenses & a few other details could be updated in `crun` too.

Hopefully they just use the upstream packages once they are merged.

@VarLad please open an issue on that

**Comment by paralin** [comment]
@tianyuanhao For the update... We still need to run AUTORECONF...

```
WARNING: 'automake-1.16' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
```

**Comment by paralin** [comment]
@VarLad Fedora, distrobox, and toolbx are all added. :)

**Comment by VarLad** [comment]
That was really fast. Thanks a lot @paralin

**Comment by tianyuanhao** [comment]
In fact, podman has not been merged into the Buildroot master branch yet.

**Comment by paralin** [comment]
@tianyuanhao that's true. It needs some love, I'm still using containerd and runc and don't have time to switch to podman right now. If you want to fix it up, PRs are welcome! And feel free to resubmit my patches to buildroot with your revisions.
