### ISSUE TITLE
devices: beagleboard & wandboard: initial testing

### ISSUE THREAD

**Issue by jim255** [skiffos/SkiffOS#193]
Wandboard
Banana Pi M2 (original Allwinner A31s)
Beagle boards running TI AM3358 & AM5729
And a yet to be released Beagle based on TI J721e (ARM64)
...
I guess I'll try to figure out the configuration...
-Jim

**Comment by jim255** [comment]
I'll gladly debug, when ready to test!
-Jim

**Comment by paralin** [comment]
Added `bananapi/m2` configuration layer.

**Comment by paralin** [comment]
Added `freescale/wandboard` configuration layer.

**Comment by paralin** [comment]
@jim255 looking forward to hearing how those two configs work for you. Let me know if you'd like a precompiled image - I can make & upload one for you.

**Comment by jim255** [comment]
I'm having difficulties building.   this is the error I'm seeing.
make[1]: Entering directory '/home/janderso/Desktop/SkiffOS-master/build'
fatal: not in a git directory
Failed to register Git Hooks.
fatal: not a git repository (or any of the parent directories): .git
make[1]: *** [Makefile:20: ensure-submodule] Error 128
make[1]: Leaving directory '/home/janderso/Desktop/SkiffOS-master/build'
make: *** [Makefile:2: configure] Error 2
What am I doing wrong?

**Comment by paralin** [comment]
@jim255 please use git to clone the repo instead of downloading it. 

"git clone https://github.com/skiffos/skiffos"

**Comment by paralin** [comment]
@jim255 That log doesn't show anything, could you instead send the skiff build output?

**Comment by jim255** [comment]
Wandboard also won't build.
[wandboard.build.log](https://github.com/skiffos/SkiffOS/files/8564229/wandboard.build.log)

**Comment by paralin** [comment]
@jim255 It seems you don't have gcc installed.

You will need to install it:

```
apt-get install build-essential
```

**Comment by jim255** [comment]
I also added suggestions into the Beagleboard community to have a look here.. Is there a command or process to build an (.img) image file without using an sd-card?

**Comment by paralin** [comment]
Yes, for example make cmd/pi/common/buildimage

That will allocate a file on disk, mount it with a loop device, then run the usual format + install commands against the loop device, then unmount the loop device.

This just makes the kernel emulate a sd card with a file.

**Comment by paralin** [comment]
@jim255 The beagleboard config for beaglebone ai is available at: https://github.com/skiffos/SkiffOS/pull/123

I need to build + test it still.

**Comment by jim255** [comment]
latest build failure freescale/wandboard config.

excerpt
t
>>> uboot 2022.04 Installing to images directory
cp -dpf /home/janderso/skiffos/workspaces/wandboard/build/uboot-2022.04/u-boot.bin /home/janderso/skiffos/workspaces/wandboard/images/
cp -dpf /home/janderso/skiffos/workspaces/wandboard/build/uboot-2022.04/u-boot-sunxi-with-spl.bin /home/janderso/skiffos/workspaces/wandboard/images/
cp: cannot stat '/home/janderso/skiffos/workspaces/wandboard/build/uboot-2022.04/u-boot-sunxi-with-spl.bin': No such file or directory
make[3]: *** [package/pkg-generic.mk:373: /home/janderso/skiffos/workspaces/wandboard/build/uboot-2022.04/.stamp_images_installed] Error 1
make[2]: *** [Makefile:23: _all] Error 2
make[2]: Leaving directory '/home/janderso/skiffos/workspaces/wandboard'
make[1]: *** [Makefile:64: compile] Error 2
make[1]: Leaving directory '/home/janderso/skiffos/build'
make: *** [Makefile:2: compile] Error 2

**Comment by paralin** [comment]
@jim255 please pull "master" and "make compile" to resume the build.

**Comment by jim255** [comment]
I did that, it's still referencing the non existent  u-boot-sunxi-with-spl.bin 
????

**Comment by paralin** [comment]
Ah, please also `rm -rf ./workspaces/wandboard/build/uboot-2022.04` @jim255

**Comment by jim255** [comment]
still no joy.....

**Comment by paralin** [comment]
@jim255 Just to confirm you've pulled latest master, deleted build/uboot-2022.04, and "make configure compile"?

I'll run a build on my end to reproduce it.

**Comment by jim255** [comment]
twice!

**Comment by paralin** [comment]
@jim255 OK, I found a issue with how uboot was configured, please pull & delete u-boot & make configure compile once more.

**Comment by paralin** [comment]
I pushed one more commit 14f892dd8f2a68b80dfe854f9dc8807fd5a1143a to fix the install script.

The build completed successfully for me this time.

**Comment by paralin** [comment]
@jim255 the beagleboard builds are ready at #123 however from my testing on a beagleboard ai, it ignores the sd card and boots from internal memory instead. I don't have a serial debug cable (ordered one) to debug that currently. Will post updates in the PR.

**Comment by jim255** [comment]
There are 2 buttons next to the network connector. Press both to reset, release order determines the persistent boot device setting.

**Comment by paralin** [comment]
@jim255 Works now correctly, `beaglebone/ai` merged to master.

**Comment by paralin** [comment]
hey @jim255 - been using the beaglebone ai w/ skiff for a week or so now, works fine! looking forward to hearing if you've had a chance to test.
