### ISSUE TITLE
Question: skiff config unset

### ISSUE THREAD

**Issue by jim255** [skiffos/SkiffOS#194]
New system, I'm setting it up to compile multiple platforms to test with.
presently will not build anything.
[U22-04-build.log](https://github.com/skiffos/SkiffOS/files/8554489/U22-04-build.log)

**Comment by paralin** [comment]
It looks like you have neither SKIFF_CONFIG nor SKITF_WORKSPACE set. Please set at least skiff config and try again.

**Comment by paralin** [comment]
@jim255 see above

**Comment by paralin** [comment]
@jim255 From your logs I can see this:

`export SKIFF__CONFIG=bananapi/m2,core/debian`

The variable is `SKIFF_CONFIG` (one underscore).
