### ISSUE TITLE
apps/compose not working with pi/3

### ISSUE THREAD

**Issue by brackling** [skiffos/SkiffOS#200]
I tried to compile an image for rpi3 using make configure with the following config:
SKIFF_CONFIG="pi/3,apps/compose" 

Unfortunately in the final buildroot .config the compose-part is missing  (BR2_PACKAGE_DOCKER_COMPOSE)

I also tested this with SKIFF_CONFIG="pi/4,apps/compose", which is working as expected

I synced the skiffos repository yesterday

**Comment by brackling** [comment]
sorry for opening this one
cant reproduce the error on a fresh installation

**Comment by paralin** [comment]
Np, also if you run "make configure" it wipes the config and recalculates it so that would probably also have fixed it. 

Thanks for the report!
