### ISSUE TITLE
Question: Why does my device show 4GB of RAM when I really have 8GB?

### ISSUE THREAD

**Issue by peterwilli** [skiffos/SkiffOS#220]
Hi there,

Not really a bug but I'm surprised to only see 4GB of RAM available:
![image](https://user-images.githubusercontent.com/1212814/180439534-257b89ef-898a-4ddd-baf0-579359f86c9b.png)
I have 8GB on the board. `htop` also only shows 4GB available. Is there a reason for this? I'm curious...

**Comment by paralin** [comment]
Mine also is 8GB but shows 4gb,

I see a `dmesg` line very early in the boot:

```
[    0.000000] Memory limited to 4096MB
```

@peterwilli Nice catch, there was a kernel parameter which limited the memory to 4096M in the boot script:

https://github.com/skiffos/SkiffOS/commit/ad85077289ad1e5a473ac1208eb9825315afe3cf

If you pull this commit, then "make cmd/odroid/common/install" once more to update it on your sd card, it should remove the limit.

**Comment by paralin** [comment]
Confirmed: that fixed it:

![image](https://user-images.githubusercontent.com/534887/180487921-3533bbae-d31d-4794-ad67-3da130f8ae6b.png)

**Comment by peterwilli** [comment]
Thanks so much, I'll try right now and super cool that I found something again, and as always checking out what you changed!

**Comment by paralin** [comment]
@peterwilli Yup, just a small mistake in the configs, easy to fix!

Glad it's working properly now 👍🏽
