### ISSUE TITLE
wsl: expose /run/WSL in the SkiffOS system

### ISSUE THREAD

**Issue by clayauld** [skiffos/SkiffOS#225]
The ```wslu``` utility doesn't seem to work as expected. The ```wslpath``` binary doesn't get installed and the WSL InteropServer appears broken.

![image](https://user-images.githubusercontent.com/2290528/182743502-6855df2b-ce22-42e7-bfa0-446ece005003.png)

![image](https://user-images.githubusercontent.com/2290528/182743510-e33fa743-d3bb-4961-a852-de5064e165d8.png)

**Comment by paralin** [comment]
For the `wslu` package we just run "make install" and the makefile provided by wslu does the installing.

It looks like wslpath was renamed to wslupath:

![image](https://user-images.githubusercontent.com/534887/182748879-bbdf8314-00a9-4740-8c22-564087cfa73e.png)

**Comment by paralin** [comment]
@clayauld It needed `/run/WSL` mounted into the skiff system, see https://github.com/skiffos/SkiffOS/pull/226

Please run the following:

```
rm -rf ./workspaces/default/build/skiff-init-*
git fetch
git checkout fix-wslu
git submodule update
make configure compile
```

... to force re-building skiff-init-squashfs.

**Comment by paralin** [comment]
@clayauld you'll also need to delete these for the Go update:

```
rm -rf ./workspaces/default/build/host-go-1*
rm -rf ./workspaces/default/host/usr/lib/go
```

**Comment by paralin** [comment]
@clayauld #226 should have fixed it - feel free to comment here if not & ill reopen.

**Comment by clayauld** [comment]
It appears that the fix doesn't properly mount ```/run/WSL -> /skiff-overlays/system/run/WSL``` as the log says...
![image](https://user-images.githubusercontent.com/2290528/182788427-92b3e459-fd5a-4361-9521-2c8c2ef238b6.png)

Comparing this to another WSL distro...
![image](https://user-images.githubusercontent.com/2290528/182788529-b16cccbe-94b3-41f5-b36a-f913fd188ea4.png)

**Comment by paralin** [comment]
Someone must mount over /run, I guess systemd. Will look into it

**Comment by paralin** [comment]
@clayauld Due to /etc/fstab containing a line mentioning /run systemd mounts a tmpfs to /run.

This must be hiding the bind mount made by skiff-init-squashfs.

**Comment by paralin** [comment]
@clayauld Let's try mounting the entire /run dir from the WSL environment and disable systemd `run.mount`

I did that on the fix-wslu branch: https://github.com/skiffos/SkiffOS/pull/227

As before we will need to rebuild skiff-init-squashfs:

```
rm -rf ./workspaces/default/build/skiff-init-*
git fetch
git checkout fix-wslu
git reset --hard origin/fix-wslu
git submodule update
make configure compile
```

**Comment by clayauld** [comment]
Hmmm.... Still seems broken.

![image](https://user-images.githubusercontent.com/2290528/183132724-5f6947e6-e0ad-4b6c-b800-dcde34b3eada.png)

**Comment by paralin** [comment]
@clayauld are you sure you're on the latest fix-wslu branch commit and have recompiled skiff init as described above?

The logs don't mention /run but they should, there's a line in the config saying to mount /run itself and it should at least show up in those logs there.

**Comment by clayauld** [comment]
Yep. You were right. 
![image](https://user-images.githubusercontent.com/2290528/183236666-e43f25c0-64f1-4694-a2d1-3d139417e8b8.png)

/run/WSL seems to be available now.

When I run the wslu commands I still get the error ```wslpath: command not found```

![image](https://user-images.githubusercontent.com/2290528/183239289-e705f9d4-26b2-4997-a122-0a8e8c71ec20.png)

I was looking at the source code for wslu and it still looks for the binary or script ```wslpath``` in the PATH. Based on another install of WSL I have running (Pengwin Linux), ```wslpath``` is a symlink to ```/init```. I'm not sure if that is common across WSL distros, but I have found stale versions of re-implimentations of wslpath. None of them seem to work as expected, however.

I can do more digging later this weekend and test other WSL distros to see how they deal with this.

**Comment by paralin** [comment]
`wslpath` is a symlink to `/init` which means that `/init` as provided by microsoft implements wslpath if it is started with `wslpath` in `$0`

`/init` doesn't exist inside the skiffos chroot but I will try to find a way to get it in there.

**Comment by paralin** [comment]
@clayauld please try `fix-wslpath` branch with https://github.com/skiffos/SkiffOS/pull/229

You will need to rebuild skiff-init-squahfs again as described above (just delete it from `build/` before make compile)

What I did was mount the original / to /mnt/wsl and then symlink wslpath to /mnt/wsl/init

**Comment by clayauld** [comment]
Okay That seems to have resolved the issues.

**Comment by paralin** [comment]
Great! Thanks for testing
