### ISSUE TITLE
Can't Compile Skiffos

### ISSUE THREAD

**Issue by Darin755** [skiffos/SkiffOS#228]
Hello,
When I try to compile Skiffos I get the following error:
![image](https://user-images.githubusercontent.com/54958995/183238386-15e27cb7-62d4-4059-9d8d-677d81a32870.png)

It seems that it is trying to fetch dropbear from [skiffos/mirror](https://github.com/skiffos/mirror) but when I look at the repo I don't see dropbear at all. Is this a bug or am I missing something? I should be able to just edit the makefile but I don't know the url to the correct repo.

**Comment by paralin** [comment]
It tries the mirror after trying the upstream source. 

If you scroll up a bit you'll see a failed request to the dropbear download servers.

Try again now and see if it works? Their servers were probably just down temporarily.

**Comment by paralin** [comment]
Regardless I mirrored dropbear. But yes, it doesn't check the mirror unless the download from the actual source fails first.
