### ISSUE TITLE
Add support for toolbox and distrobox

### ISSUE THREAD

**Issue by VarLad** [skiffos/SkiffOS#237]
Now that https://github.com/skiffos/SkiffOS/pull/235 is merged, it would be nice to have support for [toolbox](https://github.com/containers/toolbox) and [distrobox](https://github.com/89luca89/distrobox) in SkiffOS.

**Comment by paralin** [comment]
Container-toolbox package done: https://github.com/skiffos/buildroot/blob/4fdf3e80f3a04be8dfeea55ce8b030442b34b81a/package/containers-toolbox/containers-toolbox.mk

**Comment by paralin** [comment]
Containers toolbox is now available as `apps/toolbx` https://github.com/skiffos/SkiffOS/tree/master/configs/apps/toolbx

**Comment by paralin** [comment]
Distrobox package done: https://github.com/skiffos/buildroot/commit/0dc6e8f36975b4f09352da5e40f2daaad0fbd169

**Comment by paralin** [comment]
Distrobox added as `apps/distrobox`: https://github.com/skiffos/SkiffOS/tree/master/configs/apps/distrobox

And all done! :)
