### ISSUE TITLE
Add support for Fedora Linux in skiff/core

### ISSUE THREAD

**Issue by VarLad** [skiffos/SkiffOS#238]

**Comment by paralin** [comment]
Added as `core/fedora` - currently uploading the `amd64` and `arm` and `arm64` multi-arch image.

It installs the minimal-desktop-environment group on default.

**Comment by paralin** [comment]
Here's a little demo of running Fedora on the pi4: https://asciinema.org/a/516525

![image](https://user-images.githubusercontent.com/534887/186082655-05f149d5-b3e0-4300-99f3-92481ca0cde7.png)

**Comment by paralin** [comment]
And the Fedora login screen!

![image](https://user-images.githubusercontent.com/534887/186084570-c1ce1b04-bf99-4f22-8bda-d7d8bf4f881d.png)
