### ISSUE TITLE
intel/desktop: use GRUB2 to chainload rEFInd

### ISSUE THREAD

**Issue by paralin** [skiffos/SkiffOS#244]
Some platforms (Lenovo Laptops) don't detect the rEFInd EFI correctly.

Use grub2 to chainload the rEFInd binary:

```
set default="0"
set timeout="1"

menuentry "Refind" {
        chainloader /EFI/refind/refind_x64.efi
}
```

**Comment by paralin** [comment]
cc @peterwilli not sure if you have done your testing w/ intel/desktop yet but this is relevant.

**Comment by peterwilli** [comment]
I have but not the second distro thing yet. I'll try both today (I hope, have to prepare a lot for vacation)

**Comment by paralin** [comment]
Most EFi issues are solved with fixes to refind, there were some mistakes in how it was setup. I'll re-open this again if I can't figure out how to get refind to work reliably.
