### ISSUE TITLE
container tweaks needed to run KDE Plasma

### ISSUE THREAD

**Issue by bam80** [skiffos/SkiffOS#262]
Are similar container tweaks needed as those described for Distrobox?:
https://github.com/89luca89/distrobox/blob/main/docs/posts/run_latest_gnome_kde_on_distrobox.md#running-latest-plasma

If not, why is the difference?

**Comment by paralin** [comment]
No. Kde plasma runs fine. I don't know much about distrobox but I would assume the difference is we run the Wayland server inside the container rather than outside.

Feel free to open an issue if you run into any problems!

**Comment by paralin** [comment]
For one, SkiffOS runs a systemd instance in the container, so forwarding to the parent instance is unnecessary.

Besides that, yes, a lot of work has been put into making SkiffOS core run any distribution correctly in the container without needing any modifications.

**Comment by bam80** [comment]
> No. Kde plasma runs fine.

What container you tried? I didn't find pre-ready Desktop Plasma containers here, so you installed the Plasma packages in one of the existing I guess?

**Comment by paralin** [comment]
Yes. Nothing special, all you need to do is apt install it, or whatever package manager. I've tried fedora, debian, and Gentoo with kde.
