### ISSUE TITLE
skiff-core: add cachyos

### ISSUE THREAD

**Issue by osevan** [skiffos/SkiffOS#263]
Could you try arch based cachyos functionality with skiffos? 

Thanks and

Best regards

**Comment by paralin** [comment]
I guess you mean adding the patches from here:

 - https://github.com/CachyOS/linux-cachyos

I could possibly add it as a buildroot package which adds the patches to the buildroot linux patches list

**Comment by osevan** [comment]
> I guess you mean adding the patches from here:
> 
>     * https://github.com/CachyOS/linux-cachyos
> 
> 
> I could possibly add it as a buildroot package which adds the patches to the buildroot linux patches list

Ehm no, not the patches,  because its kernel patches,  i dont think you could do containerized kernels work, because containers using host kernel.

But, as distribution inside container like gentoo and debian,  you could try to build.


Cachyos is arch based distribution with nice repository. 
When someone want use cachyos repository,  they could install cachyos image, with optimzed pkgs.

**Comment by paralin** [comment]
Ok, I understand. It can be added as a core config. However, the patches with the other scheduler (bore) can actually be added to skiffos since SkiffOS compiles its own kernel. (depending on the target system)

**Comment by paralin** [comment]
Closing as out-of-scope for now
