### ISSUE TITLE
allwinner/nehza: BR2_TARGET_SUN20I_D1_SPL became a legacy option, breaking the build

### ISSUE THREAD

**Issue by Flowdalic** [skiffos/SkiffOS#283]
The allwinner/nehza target does no longer work, probably because after updating buildroot's git submodule, [the BR2_TARGET_SUN20I_D1_SPL became a legacy option](https://github.com/skiffos/buildroot/blob/e219f39c9a9c6f2b877bafcb5925bf953d470c79/Config.in.legacy#L288-L293).

**Comment by paralin** [comment]
... just removed the D1_SPL=y as well to fix the build: https://github.com/skiffos/SkiffOS/commit/72feeaa8b854d4bd778ec2420cd72d08aa071489 forgot to do it before.
