### ISSUE TITLE
skiff-init folder not found on visionfivev1 install

### ISSUE THREAD

**Issue by sdanfa** [skiffos/SkiffOS#298]
`root@debSKIFF:~/SkiffOS# make cmd/starfive/common/install
make[1]: Entering directory '/root/SkiffOS/build'
make[2]: Entering directory '/root/SkiffOS/configs/starfive/common/extensions'
Using extlinux.conf at /root/SkiffOS/configs/starfive/visionfive/resources/boot-scripts/extlinux.conf
Mounting /dev/sdb1 to /root/SkiffOS/workspaces/default/output/mounts/tmp.tBqXjm41Pj/persist...
Copying files...
sending incremental file list
./
modules.squashfs

sent 4,596,962 bytes  received 38 bytes  9,194,000.00 bytes/sec
total size is 4,595,712  speedup is 1.00
sending incremental file list
rsync: [sender] change_dir "/root/SkiffOS/workspaces/default/images/./skiff-init" failed: No such file or directory (2)

sent 19 bytes  received 12 bytes  62.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1338) [sender=3.2.7]
Unmounting /root/SkiffOS/workspaces/default/output/mounts/tmp.tBqXjm41Pj/persist...
make[2]: *** [Makefile:5: install] Error 23
make[2]: Leaving directory '/root/SkiffOS/configs/starfive/common/extensions'
make[1]: *** [Makefile:10: cmd/starfive/common/install] Error 2
make[1]: Leaving directory '/root/SkiffOS/build'
make: *** [Makefile:2: cmd/starfive/common/install] Error 2
`

**Comment by paralin** [comment]
Fixed as of 6a68b8484b549f33a32fcde43419f04b77ff2f4e

Thanks!
