### ISSUE TITLE
intel/desktop build fails

### ISSUE THREAD

**Issue by clayauld** [skiffos/SkiffOS#311]
![image](https://github.com/skiffos/SkiffOS/assets/2290528/72eccd8c-d171-4884-ab06-65d23f85a4a7)

I'm seeing this error on a fresh pull of the repo and attempting to build the intel/desktop variant of the image.

**Comment by clayauld** [comment]
Looks like I may have stumbled on the buildroot patch for this issue:

https://lore.kernel.org/buildroot/20240418135615.457970-1-giulio.benetti@benettiengineering.com/T/

**Comment by paralin** [comment]
Thanks I'll apply it.

**Comment by clayauld** [comment]
Thanks! I did confirm this patch fixed the build issues.
