### ISSUE TITLE
posibility of running glibc compiled OS on top of buildroot compiled for uclibc?

### ISSUE THREAD

**Issue by krzysztofkuczek** [skiffos/SkiffOS#322]
Hi,
I wonder if it would be possible to run os like ubuntu/debian on top of buildroot which is using uclibc.
Thinking about the boards like milk-v or luckfox, which provides access to the TPU/CSI/Camera only using closed source libs compiled for uclibc. 
It would be cool making possible using tools like opencv required glibc...
Regards
Kris

**Comment by paralin** [comment]
You can, with Docker. But I think it's actually a better idea to do it the other way around. Put the camera drivers inside a docker container running uclibc. I haven't tried building w uclibc recently but it should theoretically work. feel free to try it and let me know if you run into any problems!

**Comment by krzysztofkuczek** [comment]
Thank you
